-- 0012_seed_nearby_default_services.sql
--
-- sort_order uses gaps of 100.
-- homepage_order uses gaps of 10.

INSERT INTO services (
  service_code,
  service_type,
  category,
  sub_category,
  name,
  description,
  icon,
  color,
  workflow_type,
  owner_shop_code,
  enabled,
  sort_order,
  homepage_order
)
VALUES
  (
    'NEARBY_PRINT',
    'system',
    'nearby',
    'documents_printing',
    'Print',
    'Find nearby printing, photocopying, scanning, and related document services.',
    '🖨️',
    '#2563eb',
    'generic',
    NULL,
    1,
    100,
    10
  ),
  (
    'NEARBY_GROCERY',
    'system',
    'nearby',
    'daily_needs',
    'Grocery',
    'Find nearby grocery stores, vegetable sellers, and daily-needs shops.',
    '🥬',
    '#16a34a',
    'generic',
    NULL,
    1,
    200,
    20
  ),
  (
    'NEARBY_MEDICAL',
    'system',
    'nearby',
    'health',
    'Medical',
    'Find nearby pharmacies, medical stores, clinics, and health-related services.',
    '💊',
    '#dc2626',
    'generic',
    NULL,
    1,
    300,
    30
  ),
  (
    'NEARBY_TUITION',
    'system',
    'nearby',
    'education',
    'Tuition',
    'Find nearby tutors, coaching centers, and educational support services.',
    '🎓',
    '#7c3aed',
    'generic',
    NULL,
    1,
    400,
    40
  ),
  (
    'NEARBY_FOOD',
    'system',
    'nearby',
    'food_dining',
    'Food',
    'Find nearby restaurants, tiffin services, snacks, and prepared food.',
    '🍱',
    '#ea580c',
    'generic',
    NULL,
    1,
    500,
    50
  ),
  (
    'NEARBY_BANKING',
    'system',
    'nearby',
    'financial_services',
    'Banking',
    'Find nearby banking correspondents, ATMs, payment, and financial-service points.',
    '🏦',
    '#0369a1',
    'generic',
    NULL,
    1,
    600,
    60
  ),
  (
    'NEARBY_COURIER',
    'system',
    'nearby',
    'delivery_logistics',
    'Courier',
    'Find nearby courier, parcel, postal, and delivery-service providers.',
    '📦',
    '#b45309',
    'generic',
    NULL,
    1,
    700,
    70
  ),
  (
    'NEARBY_COMPUTER',
    'system',
    'nearby',
    'technology',
    'Computer',
    'Find nearby computer shops, internet centers, accessories, and technical services.',
    '💻',
    '#0891b2',
    'generic',
    NULL,
    1,
    800,
    80
  ),
  (
    'NEARBY_REPAIR',
    'system',
    'nearby',
    'repair_services',
    'Repair',
    'Find nearby repair services for phones, computers, appliances, and other devices.',
    '🔧',
    '#475569',
    'generic',
    NULL,
    1,
    900,
    90
  ),
  (
    'NEARBY_MAPS',
    'system',
    'nearby',
    'discovery',
    'Maps',
    'Explore additional nearby businesses and services using location-based search.',
    '🗺️',
    '#0f766e',
    'generic',
    NULL,
    1,
    1000,
    100
  )
ON CONFLICT(service_code)
DO UPDATE SET
  service_type = excluded.service_type,
  category = excluded.category,
  sub_category = excluded.sub_category,
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  color = excluded.color,
  workflow_type = excluded.workflow_type,
  owner_shop_code = excluded.owner_shop_code,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order,
  homepage_order = excluded.homepage_order,
  updated_at = CURRENT_TIMESTAMP;
